### ISSUE TITLE
ERROR [OsmHistoryImporter.launch()]  Unknown error

### ISSUE THREAD

**Issue by ktjaco** [SGroe/vgi-analytics-framework#1]
Hi, I've encountered the following error when I run the following command when trying to generate VGI operations. I can't seem to get past this error. Any help would be appreciated.

```
user@geo:~/vgi-analytics-framework/build$ java -jar vgi-analytics-framework-0.1.jar -importer -o ../history-latest.osm.pbf -s ../output/

log4j:WARN Continuable parsing error 24 and column 15
log4j:WARN Element type "log4j:configuration" must be declared.
log4j:WARN Continuable parsing error 29 and column 68
log4j:WARN Element type "appender" must be declared.
log4j:WARN Continuable parsing error 30 and column 73
log4j:WARN Element type "errorHandler" must be declared.
log4j:WARN Continuable parsing error 32 and column 45
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 33 and column 43
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 34 and column 50
log4j:WARN Element type "layout" must be declared.
log4j:WARN Continuable parsing error 35 and column 87
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 40 and column 8
log4j:WARN Element type "root" must be declared.
log4j:WARN Continuable parsing error 41 and column 28
log4j:WARN Element type "priority" must be declared.
log4j:WARN Continuable parsing error 42 and column 33
log4j:WARN Element type "appender-ref" must be declared.
log4j: reset attribute= "".
log4j: Threshold ="".
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Setting property [target] to [System.out].
log4j: Setting property [threshold] to [DEBUG].
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{HH:mm:ss,SSS} %-5p [%C{1}.%M()]  %m%n].
log4j: Adding appender named [CONSOLE] to category [root].
15:12:59,523 INFO  [AbstractApplicationContext.prepareRefresh()]  Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@504bae78: startup date [Sun Mar 05 15:12:59 EST 2017]; root of context hierarchy
15:12:59,556 INFO  [XmlBeanDefinitionReader.loadBeanDefinitions()]  Loading XML bean definitions from class path resource [application-context-osm-op-generator.xml]
[Fatal Error] :1:1: Content is not allowed in prolog.
org.xml.sax.SAXParseException; systemId: file:/home/user/vgi-analytics-framework/build/../output/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.pipeline.impl.VgiPipelineSettings.loadSettings(VgiPipelineSettings.java:189)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.application.OsmHistoryImporter.launch(OsmHistoryImporter.java:96)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.application.VgiAnalyticsFramework.main(VgiAnalyticsFramework.java:46)
15:13:00,231 INFO  [VgiPipelineSettings.loadSettings()]  Settings 'Default' loaded
15:13:00,245 INFO  [VgiOperationGeneratorOsmImpl.<init>()]  Initialze VGI Operation Generator
15:13:00,251 INFO  [VgiOperationGeneratorOsmNodeImpl.<init>()]  Initialze VGI Node Operation Generator
[Fatal Error] :1:1: Content is not allowed in prolog.
org.xml.sax.SAXParseException; systemId: file:/home/user/vgi-analytics-framework/build/../output/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.pipeline.impl.VgiPipelineSettings.loadSettings(VgiPipelineSettings.java:189)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.application.OsmHistoryImporter.launch(OsmHistoryImporter.java:102)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.application.VgiAnalyticsFramework.main(VgiAnalyticsFramework.java:46)
15:13:00,268 INFO  [VgiPipelineSettings.loadSettings()]  Settings 'Default' loaded
15:13:00,720 INFO  [VgiOperationGeneratorDataHandlerImpl.process()]  Output path: null
15:13:00,721 INFO  [VgiOperationGeneratorDataHandlerImpl.process()]  Start node phase
15:13:00,723 INFO  [AbstractApplicationContext.doClose()]  Closing org.springframework.context.support.ClassPathXmlApplicationContext@504bae78: startup date [Sun Mar 05 15:12:59 EST 2017]; root of context hierarchy
15:13:00,726 ERROR [OsmHistoryImporter.launch()]  Unknown error
java.lang.NullPointerException
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.model.vgi.impl.VgiFeatureImpl.filterByTag(VgiFeatureImpl.java:171)
	at at.salzburgresearch.vgi.vgianalyticsframework.osm.importer.impl.VgiOperationGeneratorDataHandlerImpl.enqueueOperations(VgiOperationGeneratorDataHandlerImpl.java:155)
	at at.salzburgresearch.vgi.vgianalyticsframework.osm.importer.impl.VgiOperationGeneratorDataHandlerImpl.process(VgiOperationGeneratorDataHandlerImpl.java:99)
	at at.salzburgresearch.vgi.vgianalyticsframework.osm.importer.impl.OsmPbfParser.parseDense(OsmPbfParser.java:127)
	at org.openstreetmap.osmosis.osmbinary.BinaryParser.parse(BinaryParser.java:124)
	at org.openstreetmap.osmosis.osmbinary.BinaryParser.handleBlock(BinaryParser.java:68)
	at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:135)
	at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.application.OsmHistoryImporter.launch(OsmHistoryImporter.java:104)
	at at.salzburgresearch.vgi.vgianalyticsframework.activityanalysis.application.VgiAnalyticsFramework.main(VgiAnalyticsFramework.java:46)
usage: java -jar vgi-activity-1.0.jar [OPTION]...
 -analysis,--vgi_analysis               VGI analysis
 -c,--crs <crs>                         crs
 -d,--directory <home_directory_file>   home directory file
 -ea,--east <east_bound>                east bound
 -h,--help                              Display this help page
 -importer,--osm_importer               OSM Importer
 -no,--north <north_bound>              north bound
 -o,--osm <osm_history_file>            osm history file
 -p,--polygons <polygon_file>           polygon file
 -quadtree,--quadtree_builder           Quadtree Builder
 -r,--rastersize <raster_size>          raster size
 -raster,--hexagonal_raster_generator   Hexagonal raster generator
 -s,--settings <settings_file>          settings file
 -so,--south <south_bound>              south bound
 -we,--west <west_bound>                west bound
```

**Comment by SGroe** [comment]
Hi,

according to your log output, you set the settings parameter to 
`-s ../output/`

The setting parameter should set the path to the settings XML file (e.g. `-s ../settings/settings_op_generator.xml`).

**Comment by ktjaco** [comment]
@SGroe Thanks for this! I realized that I forgot to specify the .xml file.
